//---------------------------------------------------------------------------

#ifndef bum_sett_frmH
#define bum_sett_frmH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <IdBaseComponent.hpp>
#include <IdComponent.hpp>
#include <IdUDPBase.hpp>
#include <IdUDPClient.hpp>
//---------------------------------------------------------------------------
class Tbum_settings : public TForm
{
__published:	// IDE-managed Components
        TLabel *Label1;
        TLabel *bum_object;
        TLabel *date_label;
        TLabel *Label2;
        TLabel *date_from_bum;
        TLabel *time_from_bum;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *sun_vector_x;
        TLabel *sun_vector_y;
        TLabel *sun_vector_z;
        TLabel *Label7;
        TLabel *reg_st;
        TLabel *Label8;
        TLabel *su_num;
        TLabel *Label9;
        TLabel *su_styk_num;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *pr_st_bum;
        TLabel *pr_m_y_bum;
        TLabel *regym_bum;
        TGroupBox *tpk_group;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label15;
        TLabel *Label16;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label21;
        TLabel *Label22;
        TLabel *Label23;
        TLabel *Label24;
        TLabel *Label25;
        TLabel *Label26;
        TLabel *Label27;
        TLabel *Label28;
        TLabel *Label29;
        TLabel *Label30;
        TLabel *Label31;
        TLabel *q_ssk_tk_0;
        TLabel *q_ssk_tk_1;
        TLabel *q_ssk_tk_2;
        TLabel *q_ssk_tk_3;
        TLabel *tk_mass;
        TTimer *bum_desc;
        TComboBox *desc;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label34;
        TLabel *Label35;
        TLabel *Label36;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *Label58;
        TLabel *Label59;
        TLabel *Label60;
        TIdUDPClient *bum_10;
        TButton *Button1;
        TLabel *Label61;
        TGroupBox *GroupBox1;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TLabel *Label65;
        TLabel *Label66;
        TLabel *Label67;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *Label71;
        TLabel *Label72;
        TLabel *Label73;
        TLabel *Label74;
        TLabel *Label75;
        TTimer *Timer1;
        TLabel *Label76;
        TLabel *Label77;
        TTimer *Timer2;
        TGroupBox *GroupBox2;
        TGroupBox *GroupBox3;
        TLabel *Label78;
        TLabel *Label79;
        TLabel *Label80;
        TLabel *Label81;
        TLabel *Label82;
        TLabel *Label83;
        TLabel *Label84;
        TLabel *Label85;
        TLabel *Label86;
        TLabel *Label87;
        TLabel *Label88;
        TLabel *Label89;
        TLabel *Label91;
        TLabel *Label92;
        TLabel *Label93;
        TLabel *Label94;
        TLabel *Label95;
        TLabel *Label96;
        TLabel *Label97;
        TLabel *Label98;
        TLabel *Label99;
        TLabel *Label100;
        TLabel *Label102;
        TLabel *Label103;
        TLabel *Label104;
        TLabel *Label105;
        TLabel *Label106;
        TLabel *Label107;
        TLabel *Label108;
        TLabel *Label109;
        TLabel *Label110;
        TLabel *Label111;
        TLabel *Label112;
        TLabel *Label113;
        TLabel *Label114;
        TLabel *Label115;
        TLabel *Label116;
        TLabel *Label117;
        TLabel *Label118;
        TLabel *Label119;
        TLabel *Label120;
        TLabel *Label121;
        TLabel *Label122;
        TLabel *Label123;
        TLabel *Label124;
        TLabel *Label125;
        TLabel *Label126;
        TLabel *Label127;
        TLabel *Label128;
        TLabel *Label129;
        TLabel *Label130;
        TLabel *Label131;
        TLabel *Label132;
        TLabel *Label133;
        TEdit *Edit1;
        TButton *Button2;
        TGroupBox *GroupBox4;
        TLabel *Label134;
        TLabel *Label135;
        TLabel *Label136;
        TLabel *Label137;
        TLabel *Label138;
        TGroupBox *GroupBox5;
        TLabel *Label139;
        TLabel *Label140;
        TLabel *Label141;
        TLabel *Label142;
        TGroupBox *GroupBox6;
        TLabel *Label90;
        TLabel *Label101;
        TLabel *Label143;
        TLabel *Label144;
        TLabel *Label145;
        TLabel *Label146;
        TLabel *Label147;
        TLabel *Label148;
        TLabel *Label149;
        TLabel *Label150;
        TLabel *Label151;
        TLabel *Label152;
        TLabel *Label153;
        TLabel *Label154;
        TLabel *Label155;
        TLabel *Label156;
        TLabel *Label157;
        TLabel *Label158;
        TLabel *Label159;
        TLabel *Label160;
        TLabel *Label161;
        TLabel *Label162;
        TLabel *Label163;
        TLabel *Label164;
        TLabel *Label165;
        TLabel *Label166;
        TLabel *Label167;
        TLabel *Label168;
        TLabel *Label169;
        TLabel *Label170;
        TLabel *Label171;
        TLabel *Label172;
        TLabel *Label173;
        TLabel *Label174;
        void __fastcall bum_descTimer(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall Timer1Timer(TObject *Sender);
        void __fastcall Timer2Timer(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall Tbum_settings(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE Tbum_settings *bum_settings;
//---------------------------------------------------------------------------
#endif
