//---------------------------------------------------------------------------

#ifndef debug_bum_frmH
#define debug_bum_frmH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
//---------------------------------------------------------------------------
class Tbum_debug : public TForm
{
__published:	// IDE-managed Components
        TPageControl *PageControl1;
        TTabSheet *TabSheet1;
        TTabSheet *TabSheet2;
        TTabSheet *TabSheet3;
        TTabSheet *TabSheet4;
        TTabSheet *TabSheet5;
        TLabel *Label1;
        TLabel *Label2;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label7;
        TLabel *Label8;
        TLabel *Label9;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label25;
        TLabel *p_1;
        TLabel *p_2;
        TLabel *p_4;
        TLabel *p_3;
        TLabel *p_8;
        TLabel *p_7;
        TLabel *p_6;
        TLabel *p_5;
        TLabel *p_12;
        TLabel *p_11;
        TLabel *p_10;
        TLabel *p_9;
        TLabel *p_14;
        TLabel *p_13;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label65;
        TLabel *Label66;
        TLabel *Label67;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *p_15;
        TLabel *p_16;
        TLabel *p_18;
        TLabel *p_17;
        TLabel *p_22;
        TLabel *p_21;
        TLabel *p_20;
        TLabel *p_19;
        TLabel *p_26;
        TLabel *p_25;
        TLabel *p_24;
        TLabel *p_23;
        TLabel *p_28;
        TLabel *p_27;
        TLabel *Label85;
        TLabel *Label86;
        TLabel *Label87;
        TLabel *Label88;
        TLabel *Label89;
        TLabel *Label90;
        TLabel *Label91;
        TLabel *Label92;
        TLabel *Label93;
        TLabel *Label94;
        TLabel *Label95;
        TLabel *Label96;
        TLabel *Label97;
        TLabel *Label98;
        TLabel *Label99;
        TLabel *Label100;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *Label58;
        TLabel *Label59;
        TLabel *Label60;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TLabel *Label101;
        TLabel *Label61;
        TLabel *Label102;
        TLabel *Label103;
        TLabel *Label104;
        TLabel *Label105;
        TLabel *Label106;
        TLabel *p_29;
        TLabel *p_30;
        TLabel *p_32;
        TLabel *p_31;
        TLabel *p_36;
        TLabel *p_35;
        TLabel *p_34;
        TLabel *p_33;
        TLabel *p_40;
        TLabel *p_39;
        TLabel *p_38;
        TLabel *p_37;
        TLabel *p_42;
        TLabel *p_41;
        TLabel *Label121;
        TLabel *Label122;
        TLabel *Label123;
        TLabel *Label124;
        TLabel *Label125;
        TLabel *Label126;
        TLabel *Label127;
        TLabel *Label128;
        TLabel *Label129;
        TLabel *Label130;
        TLabel *Label131;
        TLabel *Label132;
        TLabel *Label133;
        TLabel *Label134;
        TLabel *Label135;
        TLabel *Label136;
        TLabel *Label137;
        TLabel *Label138;
        TLabel *Label139;
        TLabel *Label140;
        TLabel *Label141;
        TLabel *Label142;
        TLabel *Label143;
        TLabel *Label144;
        TLabel *Label145;
        TLabel *Label146;
        TLabel *Label147;
        TLabel *Label148;
        TLabel *Label149;
        TLabel *Label150;
        TLabel *Label151;
        TLabel *p_43;
        TLabel *p_44;
        TLabel *p_46;
        TLabel *p_45;
        TLabel *p_50;
        TLabel *p_49;
        TLabel *p_48;
        TLabel *p_47;
        TLabel *p_54;
        TLabel *p_53;
        TLabel *p_52;
        TLabel *p_51;
        TLabel *p_56;
        TLabel *p_55;
        TLabel *Label166;
        TLabel *Label167;
        TLabel *Label168;
        TLabel *Label169;
        TLabel *Label170;
        TLabel *Label171;
        TLabel *Label172;
        TLabel *Label173;
        TLabel *Label174;
        TLabel *Label175;
        TLabel *Label176;
        TLabel *Label177;
        TLabel *Label178;
        TLabel *Label179;
        TLabel *Label180;
        TLabel *Label181;
        TLabel *Label182;
        TLabel *Label183;
        TLabel *Label184;
        TLabel *Label185;
        TLabel *Label186;
        TLabel *Label187;
        TLabel *Label188;
        TLabel *Label189;
        TLabel *Label190;
        TLabel *Label191;
        TLabel *Label192;
        TLabel *Label193;
        TLabel *Label196;
        TLabel *p_57;
        TLabel *p_58;
        TLabel *p_60;
        TLabel *p_59;
        TLabel *p_63;
        TLabel *p_62;
        TLabel *p_61;
        TLabel *p_68;
        TLabel *p_67;
        TLabel *p_66;
        TLabel *p_65;
        TLabel *p_69;
        TLabel *Label211;
        TLabel *Label212;
        TLabel *Label213;
        TLabel *Label214;
        TLabel *Label216;
        TLabel *Label217;
        TLabel *Label218;
        TLabel *Label219;
        TLabel *Label220;
        TLabel *Label221;
        TLabel *Label222;
        TLabel *Label224;
        TLabel *Label225;
        TLabel *Label226;
        TLabel *Label227;
        TLabel *Label228;
        TLabel *Label229;
        TLabel *Label230;
        TLabel *Label231;
        TLabel *Label232;
        TLabel *Label233;
        TLabel *Label234;
        TLabel *Label235;
        TButton *Button1;
        TButton *Button2;
        TButton *Button3;
        TButton *Button4;
        TButton *Button5;
        TButton *Button6;
        TButton *Button7;
        TButton *Button8;
        TButton *Button9;
        TButton *Button10;
        TButton *Button11;
        TButton *Button12;
        TButton *Button13;
        TButton *Button14;
        TButton *Button15;
        TListBox *ListBox1;
        TTimer *Timer1;
        TLabel *Label15;
        TButton *Button16;
        TButton *Button17;
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
        void __fastcall Button3Click(TObject *Sender);
        void __fastcall Button4Click(TObject *Sender);
        void __fastcall Button5Click(TObject *Sender);
        void __fastcall Button6Click(TObject *Sender);
        void __fastcall Button7Click(TObject *Sender);
        void __fastcall Button8Click(TObject *Sender);
        void __fastcall Button9Click(TObject *Sender);
        void __fastcall Button10Click(TObject *Sender);
        void __fastcall Button11Click(TObject *Sender);
        void __fastcall Button12Click(TObject *Sender);
        void __fastcall Button13Click(TObject *Sender);
        void __fastcall Button14Click(TObject *Sender);
        void __fastcall Button15Click(TObject *Sender);
        void __fastcall Timer1Timer(TObject *Sender);
        void __fastcall Button16Click(TObject *Sender);
        void __fastcall Button17Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall Tbum_debug(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE Tbum_debug *bum_debug;
//---------------------------------------------------------------------------
#endif
