object zakon_upr_frm: Tzakon_upr_frm
  Left = 63
  Top = 152
  Width = 920
  Height = 491
  Caption = #1047#1072#1082#1086#1085' '#1091#1087#1088#1072#1074#1083#1077#1085#1080#1103
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object zakon_uprav: TChart
    Left = 0
    Top = 0
    Width = 904
    Height = 432
    AllowPanning = pmNone
    AllowZoom = False
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    BackWall.Color = clLime
    BottomWall.Brush.Color = clWhite
    BottomWall.Color = clSilver
    Foot.Alignment = taRightJustify
    Foot.Text.Strings = (
      #1088)
    Foot.Visible = False
    MarginBottom = 0
    MarginLeft = 0
    MarginTop = 5
    Title.AdjustFrame = False
    Title.Alignment = taLeftJustify
    Title.Font.Charset = RUSSIAN_CHARSET
    Title.Font.Color = clWhite
    Title.Font.Height = -12
    Title.Font.Name = 'Consolas'
    Title.Font.Style = []
    Title.Frame.Style = psDashDot
    Title.Text.Strings = (
      '     '#1052'/'#1057)
    BackColor = clLime
    BottomAxis.Automatic = False
    BottomAxis.AutomaticMaximum = False
    BottomAxis.AutomaticMinimum = False
    BottomAxis.Axis.Color = clWhite
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 4
    BottomAxis.LabelsFont.Charset = RUSSIAN_CHARSET
    BottomAxis.LabelsFont.Color = clWhite
    BottomAxis.LabelsFont.Height = -12
    BottomAxis.LabelsFont.Name = 'Consolas'
    BottomAxis.LabelsFont.Style = []
    BottomAxis.LabelsMultiLine = True
    BottomAxis.LabelStyle = talValue
    BottomAxis.Maximum = 25
    BottomAxis.MinorTicks.Color = clAqua
    BottomAxis.MinorTicks.Visible = False
    BottomAxis.RoundFirstLabel = False
    BottomAxis.TickLength = 0
    BottomAxis.TickOnLabelsOnly = False
    BottomAxis.Ticks.Color = clAqua
    ClipPoints = False
    DepthAxis.LabelsOnAxis = False
    DepthAxis.RoundFirstLabel = False
    LeftAxis.Axis.Color = clWhite
    LeftAxis.LabelsFont.Charset = RUSSIAN_CHARSET
    LeftAxis.LabelsFont.Color = clWhite
    LeftAxis.LabelsFont.Height = -12
    LeftAxis.LabelsFont.Name = 'Consolas'
    LeftAxis.LabelsFont.Style = []
    LeftAxis.LabelStyle = talValue
    LeftAxis.StartPosition = 2
    LeftAxis.RoundFirstLabel = False
    Legend.Visible = False
    RightAxis.RoundFirstLabel = False
    ScaleLastPage = False
    TopAxis.Automatic = False
    TopAxis.AutomaticMaximum = False
    TopAxis.AutomaticMinimum = False
    TopAxis.Axis.Visible = False
    TopAxis.LabelsFont.Charset = RUSSIAN_CHARSET
    TopAxis.LabelsFont.Color = clAqua
    TopAxis.LabelsFont.Height = -11
    TopAxis.LabelsFont.Name = 'Consolas'
    TopAxis.LabelsFont.Style = []
    TopAxis.LabelStyle = talValue
    TopAxis.RoundFirstLabel = False
    TopAxis.TickOnLabelsOnly = False
    TopAxis.Visible = False
    View3D = False
    View3DWalls = False
    Align = alClient
    BevelWidth = 0
    Color = 4194304
    TabOrder = 0
    object GroupBox1: TGroupBox
      Left = 840
      Top = -1
      Width = 53
      Height = 28
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 0
      object Label1: TLabel
        Left = 5
        Top = 9
        Width = 42
        Height = 15
        Caption = '300000'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Consolas'
        Font.Style = []
        ParentFont = False
      end
    end
    object Button1: TButton
      Left = 808
      Top = 5
      Width = 25
      Height = 20
      Caption = 'Cle'
      TabOrder = 1
      OnClick = Button1Click
    end
    object Series1: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = clRed
      Title = 'rad_1'
      LinePen.Color = clRed
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series2: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = 4210816
      Title = 'rad_2'
      LinePen.Color = 4210816
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series3: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = clRed
      Title = 'rad_3'
      LinePen.Color = clRed
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series4: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = clYellow
      Title = 'rad_4'
      LinePen.Color = clYellow
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series5: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = clLime
      Title = 'rad_5'
      LinePen.Color = clLime
      LinePen.Style = psDashDot
      LinePen.Width = 2
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series6: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Clip = True
      Marks.Visible = False
      SeriesColor = clYellow
      Title = 'rad_6'
      LinePen.Color = clYellow
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series7: TFastLineSeries
      Marks.Arrow.Visible = False
      Marks.ArrowLength = 8
      Marks.BackColor = 4194304
      Marks.Clip = True
      Marks.Font.Charset = RUSSIAN_CHARSET
      Marks.Font.Color = clAqua
      Marks.Font.Height = -12
      Marks.Font.Name = 'Consolas'
      Marks.Font.Style = []
      Marks.Frame.Visible = False
      Marks.Style = smsXValue
      Marks.Visible = True
      SeriesColor = clWhite
      Title = 'AxisX'
      LinePen.Color = clWhite
      LinePen.Width = 2
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series8: TPointSeries
      Cursor = crDrag
      Marks.Arrow.Visible = False
      Marks.ArrowLength = 13
      Marks.Clip = True
      Marks.Frame.Style = psDot
      Marks.Style = smsValue
      Marks.Visible = True
      SeriesColor = clGreen
      ShowInLegend = False
      Title = 'TK'
      Pointer.HorizSize = 6
      Pointer.InflateMargins = True
      Pointer.Style = psCircle
      Pointer.VertSize = 6
      Pointer.Visible = True
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series9: TFastLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clWhite
      LinePen.Color = clWhite
      LinePen.Width = 2
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
    object Series10: TFastLineSeries
      Marks.Arrow.Visible = False
      Marks.ArrowLength = 8
      Marks.BackColor = 4194304
      Marks.Clip = True
      Marks.Font.Charset = RUSSIAN_CHARSET
      Marks.Font.Color = clAqua
      Marks.Font.Height = -12
      Marks.Font.Name = 'Consolas'
      Marks.Font.Style = []
      Marks.Frame.Visible = False
      Marks.Style = smsXValue
      Marks.Visible = True
      SeriesColor = clWhite
      Title = 'AxisX'
      LinePen.Color = clWhite
      LinePen.Width = 2
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object MainMenu1: TMainMenu
    Left = 32
    object N1: TMenuItem
      Caption = #1052#1072#1089#1096#1090#1072#1073
      object N3001: TMenuItem
        Caption = '300'
        OnClick = MainFormN3001Click
      end
      object N7501: TMenuItem
        Caption = '750'
        OnClick = N7501Click
      end
      object N15001: TMenuItem
        Caption = '1 500'
        OnClick = N15001Click
      end
      object N30001: TMenuItem
        Caption = '3 000'
        OnClick = N30001Click
      end
      object N60001: TMenuItem
        Caption = '6 000'
        OnClick = N60001Click
      end
      object N150001: TMenuItem
        Caption = '15 000'
      end
    end
    object N2: TMenuItem
      Caption = #1055#1088#1080#1085#1103#1090#1100' '#1044
      OnClick = N2Click
    end
  end
  object Timer1: TTimer
    OnTimer = Timer1Timer
  end
end
