//---------------------------------------------------------------------------

#ifndef SOTR_frmH
#define SOTR_frmH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Buttons.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <ComCtrls.hpp>
//---------------------------------------------------------------------------
class Tsotr : public TForm
{
__published:	// IDE-managed Components
        TPageControl *PageControl1;
        TTabSheet *TabSheet1;
        TTabSheet *TabSheet2;
        TGroupBox *GroupBox1;
        TLabel *Label24;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label23;
        TLabel *Label22;
        TLabel *Label16;
        TLabel *Label15;
        TLabel *Label21;
        TLabel *Label20;
        TLabel *Label18;
        TLabel *Label17;
        TLabel *Label19;
        TLabel *Label1;
        TLabel *Label2;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label7;
        TLabel *Label8;
        TLabel *Label9;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label25;
        TLabel *ts2_5;
        TLabel *Label27;
        TLabel *ts2_6;
        TLabel *Label29;
        TLabel *Label30;
        TGroupBox *GroupBox2;
        TLabel *Label31;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label34;
        TLabel *Label35;
        TLabel *Label36;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TLabel *Label44;
        TEdit *Tsa_input;
        TEdit *Tbo_input;
        TEdit *Tpo_input;
        TEdit *Tj_input;
        TEdit *Pbo_input;
        TEdit *Psa_input;
        TEdit *Tknr_ust_input;
        TEdit *Tknr_input;
        TEdit *Pkgo_input;
        TEdit *Ppo_input;
        TEdit *Ph2o_input;
        TEdit *Pknr_input;
        TEdit *Rrg_input;
        TGroupBox *GroupBox3;
        TLabel *Label43;
        TLabel *Label45;
        TLabel *Label46;
        TCheckBox *CheckBox1;
        TCheckBox *CheckBox2;
        TCheckBox *CheckBox3;
        TCheckBox *CheckBox4;
        TCheckBox *CheckBox5;
        TCheckBox *CheckBox6;
        TCheckBox *CheckBox7;
        TCheckBox *CheckBox8;
        TCheckBox *CheckBox10;
        TCheckBox *CheckBox11;
        TCheckBox *CheckBox12;
        TEdit *Edit13;
        TEdit *Edit15;
        TEdit *Edit16;
        TGroupBox *GroupBox4;
        TLabel *Label66;
        TLabel *Label74;
        TLabel *Label58;
        TLabel *Label50;
        TLabel *Label47;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *Label61;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TLabel *Label65;
        TLabel *Label67;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *Label71;
        TLabel *Label72;
        TLabel *Label73;
        TLabel *Label77;
        TLabel *Label78;
        TButton *Button1;
        TButton *Button2;
        TButton *Button3;
        TButton *Button4;
        TButton *Button5;
        TButton *Button6;
        TButton *Button7;
        TButton *Button8;
        TButton *Button9;
        TButton *Button10;
        TButton *Button11;
        TButton *Button12;
        TButton *Button13;
        TButton *Button14;
        TButton *Button17;
        TButton *Button18;
        TButton *Button19;
        TButton *Button20;
        TButton *Button21;
        TButton *Button22;
        TButton *Button23;
        TButton *Button24;
        TButton *Button25;
        TButton *Button26;
        TButton *Button27;
        TButton *Button28;
        TButton *Button29;
        TButton *Button30;
        TGroupBox *GroupBox5;
        TSpeedButton *krl_cmd1;
        TSpeedButton *krl_cmd2;
        TSpeedButton *krl_cmd3;
        TSpeedButton *krl_cmd5;
        TSpeedButton *krl_cmd4;
        TGroupBox *GroupBox6;
        TSpeedButton *SpeedButton5;
        TLabel *Label59;
        TLabel *Label60;
        TLabel *Label75;
        TImage *rrg_8;
        TImage *rrg_4;
        TImage *rrg_16;
        TLabel *Label76;
        TLabel *Label79;
        TLabel *Label80;
        TImage *str_off_pc;
        TImage *str_min_pc;
        TImage *str_max_pc;
        TLabel *Label81;
        TLabel *Label82;
        TLabel *Label83;
        TImage *cond_bo;
        TImage *cond_sa;
        TSpeedButton *SpeedButton7;
        TSpeedButton *SpeedButton8;
        TSpeedButton *SpeedButton9;
        TSpeedButton *SpeedButton10;
        TImage *vsa_off;
        TImage *vsa_on;
        TImage *vent_vsk_off;
        TImage *vent_vsk_on;
        TImage *en_vsk_off;
        TImage *en_vsk_on;
        TLabel *Label84;
        TLabel *Label85;
        TLabel *Label86;
        TGroupBox *GroupBox8;
        TComboBox *ComboBox1;
        TGroupBox *GroupBox7;
        TCheckBox *CheckBox9;
        TCheckBox *CheckBox13;
        TCheckBox *CheckBox14;
        TImage *Image1;
        TLabel *Label87;
        TLabel *Label88;
        TLabel *Label89;
        TLabel *Label90;
        TLabel *balon_sa;
        TLabel *p_sa_label;
        TLabel *Label93;
        TLabel *bo_pressure;
        TLabel *Label95;
        TLabel *Label96;
        TLabel *Label97;
        TLabel *Label98;
        TLabel *Label99;
        TLabel *Label100;
        TLabel *Label101;
        TLabel *Label102;
        TLabel *Label103;
        TLabel *Label104;
        TLabel *Label105;
        TLabel *Label106;
        TLabel *Label107;
        TLabel *Label108;
        TLabel *Label109;
        TLabel *Label110;
        TLabel *Label111;
        TLabel *Label112;
        TLabel *Label113;
        TLabel *Label114;
        TLabel *Label115;
        TLabel *Label116;
        TLabel *Label117;
        TLabel *Label118;
        TLabel *Label119;
        TTimer *model;
        TImage *ksd_eu;
        TImage *Image3;
        TImage *ksd_open;
        TImage *ksd_close;
        TImage *Image2;
        TImage *Image4;
        TTabSheet *TabSheet3;
        TButton *input_sps_data;
        TTimer *USOTimer;
        void __fastcall Label59Click(TObject *Sender);
        void __fastcall Label60Click(TObject *Sender);
        void __fastcall Label75Click(TObject *Sender);
        void __fastcall Label76Click(TObject *Sender);
        void __fastcall Label82Click(TObject *Sender);
        void __fastcall vsa_offClick(TObject *Sender);
        void __fastcall vsa_onClick(TObject *Sender);
        void __fastcall vent_vsk_offClick(TObject *Sender);
        void __fastcall vent_vsk_onClick(TObject *Sender);
        void __fastcall en_vsk_offClick(TObject *Sender);
        void __fastcall en_vsk_onClick(TObject *Sender);
        void __fastcall Label79Click(TObject *Sender);
        void __fastcall Label80Click(TObject *Sender);
        void __fastcall Label83Click(TObject *Sender);
        void __fastcall modelTimer(TObject *Sender);
        void __fastcall Image3Click(TObject *Sender);
        void __fastcall Image2Click(TObject *Sender);
        void __fastcall Image4Click(TObject *Sender);
        void __fastcall input_sps_dataClick(TObject *Sender);
        void __fastcall USOTimerTimer(TObject *Sender);
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
        void __fastcall Button4Click(TObject *Sender);
        void __fastcall Button3Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall Tsotr(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE Tsotr *sotr;
//---------------------------------------------------------------------------
#endif
